Improve filterStyledSystemProps performances
balena-io-modules/rendition pull request #1267
Opened 2021-03-16 17:54 UTC by JSReds

Improve filterStyledSystemProps performances replacing omit with pickBy

Change-type: patch

Signed-off-by: Andrea Rosci <andrear@balena.io>

---
##### Contributor checklist

- [ ] I have regenerated screenshots for any affected components with `npm run generate-screenshots`
- [ ] I have regenerated jest snapshots for any affected components with `npm run jest -- -u`

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

2021-03-16 18:01 UTC, thgreasi commented
@balena-ci rebase

2021-03-16 18:15 UTC, thgreasi requested changes

2021-03-16 18:15 UTC, thgreasi commented on src/asRendition.tsx
> +	const shouldIncludeProp = (prop: string) => !diff.has(prop);
Sorry that I missed this :(
```suggestion
	const shouldIncludeProp = (_value: unknown, prop: string) => !diff.has(prop);
```

2021-03-16 18:17 UTC, thgreasi commented on src/asRendition.tsx
> +			shouldIncludeProp,
You might also need to `npm run prettify`.

2021-03-16 20:05 UTC, thgreasi commented
Page ending up opening #1268 before seeing this.
I'm guessing that the manual for...of loop might be faster, but the `delete` might actually make it slower.
So give it a try before closing.

2021-03-18 11:59 UTC, JSReds commented
closing in favour of #1268
<img width="408" alt="Screenshot 2021-03-18 at 12 58 14" src="https://user-images.githubusercontent.com/7238159/111622730-d07e4d00-87e9-11eb-9e1d-59a2c3240648.png">

2021-03-18 12:00 UTC, JSReds commented
Closing in favour of #1268
<img width="408" alt="Screenshot 2021-03-18 at 12 58 14" src="https://user-images.githubusercontent.com/7238159/111622769-dc6a0f00-87e9-11eb-8857-11d9d7cf24a4.png">

2021-03-18 12:00 UTC, closed without merging